/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iiita.gproject.automaticelevatorsys;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.Random;
import java.util.logging.FileHandler;
//import javax.mail.MessagingException;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author anshverma
 */
public class Initfinal extends javax.swing.JFrame {
    public int idx,f,wt,n,cnt=0;   
    public final static int t = 3000;
    private int flag=0;
    Numfinal track= new Numfinal(idx,f);
    String[] doorStatus={
        "Closed",
        "Closed",
        "Opening",
        "Opening",
        "Closing",
        "Opened",
        "Closing",
        "Opened",
        "Closed",
        "Opened",
        
    };
    String[] overallStatus={
        "Lift Moving",
        "Lift Moving",
        "People Entering & Exiting",
        "People Entering & Exiting",
        "People Entering & Exiting",
        "People Entering & Exiting",
        "People Entering & Exiting",
        "People Entering & Exiting",
        "Power Drop",
        "Lift Capacity Exceeded",
    };
    /**
     * Creates new form Initfinal
     */
    public Initfinal() throws IOException{
        initComponents();
        track.setVisible(true);
        
        javax.swing.Timer timer;
        timer = new javax.swing.Timer(t, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(flag==1)
                {
                    ((Timer)e.getSource()).stop();
                }
                getContentPane().removeAll();
                try {
                    initComponents();
                } catch (IOException ex) {
                    Logger.getLogger(Initfinal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                track.idx=idx;track.f=f;
                track.getContentPane().removeAll();
                track.initComponents();
                track.validate();
                track.repaint();
                
                validate();
                repaint();
            }
        });
        timer.start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int rand(int l) {
    int pick = new Random().nextInt(l);
    return pick;
}
     public void precomp() {
        idx= rand(doorStatus.length);
        f= rand(5);
        if(idx<9)
        wt= rand(600);
        else
        wt= (int)(Math.random() * (900 - 700 + 1) + 700);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws IOException{

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doorLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        peopleLabel = new javax.swing.JLabel();
        floorLabel = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elevator Monitoring");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/door2.png")); // NOI18N
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        
        jLabel2.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(imageIcon); // NOI18N
        jLabel2.setText("Door Status :");
        
        imageIcon= new javax.swing.ImageIcon(getClass().getResource("/weight3.png")); // NOI18N
        image = imageIcon.getImage();
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);

        jLabel3.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(imageIcon);
        jLabel3.setText(" Weight :");
        
        imageIcon= new javax.swing.ImageIcon(getClass().getResource("/people1.png")); // NOI18N
        image = imageIcon.getImage();
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);

        jLabel4.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(imageIcon);
        jLabel4.setText("No. of People :");
        
        imageIcon= new javax.swing.ImageIcon(getClass().getResource("/lift3.png")); // NOI18N
        image = imageIcon.getImage();
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);

        jLabel5.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(imageIcon);
        jLabel5.setText("Floor No. :");

        imageIcon= new javax.swing.ImageIcon(getClass().getResource("/lift4.png")); // NOI18N
        image = imageIcon.getImage();
        newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);
        
        jLabel6.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(imageIcon);
        jLabel6.setText("Lift Status :");

        precomp();
        if(wt<60)
            n=1;
        else
            n= wt/50;
        
        doorLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        doorLabel.setForeground(new java.awt.Color(0, 102, 102));
        doorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doorLabel.setText(doorStatus[idx]);

        weightLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        weightLabel.setForeground(new java.awt.Color(0, 102, 102));
        weightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weightLabel.setText(Integer.toString(wt));

        peopleLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        peopleLabel.setForeground(new java.awt.Color(0, 102, 102));
        peopleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peopleLabel.setText(Integer.toString(n));

        floorLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        floorLabel.setForeground(new java.awt.Color(0, 102, 102));
        floorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorLabel.setText(Integer.toString(f));

        statLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        statLabel.setForeground(new java.awt.Color(0, 102, 102));
        statLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statLabel.setText(overallStatus[idx]);
        

        jButton1.setText("Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doorLabel)
                    .addComponent(weightLabel)
                    .addComponent(peopleLabel)
                    .addComponent(floorLabel)
                    .addComponent(statLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(doorLabel))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(weightLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(peopleLabel))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(floorLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocation(new java.awt.Point(0, 500));
        try{
            LogManager lm = LogManager.getLogManager();
            String LoggerName = Logger.GLOBAL_LOGGER_NAME;
            Logger logrep = lm.getLogger(LoggerName);
            logrep.setLevel(Level.INFO);
            logrep.setUseParentHandlers(false);

            FileHandler fh = new FileHandler("logreports.log",0,1,true);
            fh.setFormatter(new SimpleFormatter());
            fh.setLevel(Level.INFO);
            logrep.addHandler(fh);
            logrep.log(Level.INFO, "\nWeight in lift:{0}\nNumber of people:{1}\nFloor no:{2}\nOverall Status:{3}", new Object[]{wt, n, f, statLabel.getText()});
            fh.flush();
            fh.close();
            if("Power Drop".equals(statLabel.getText())){
                SendEmail sendEmail = new SendEmail();
            }
        }
        catch(IOException e){
            System.err.println(e);
        }
    }// </editor-fold>                        
     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        flag=1;
        this.dispose();
        track.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel doorLabel;
    private javax.swing.JLabel floorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel peopleLabel;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration                   
}
