/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iiita.gproject.automaticelevatorsys;

/**
 *
 * @author anshverma
 */
public class Verify extends javax.swing.JFrame {
    String authName= "admin", authPass="Password", authKey="123";
    /**
     * Creates new form Verify
     */
    public Verify() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Dialog = new javax.swing.JDialog();
        curFloor4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        curFloor = new javax.swing.JLabel();
        curFloor1 = new javax.swing.JLabel();
        curFloor2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        givenName = new javax.swing.JTextField();
        givenKey = new javax.swing.JPasswordField();
        curFloor3 = new javax.swing.JLabel();
        givenPass = new javax.swing.JPasswordField();

        Dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog.setBounds(new java.awt.Rectangle(0, 23, 350, 250));
        Dialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        curFloor4.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        curFloor4.setText("Invalid username or password.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 30, 0, 0);
        Dialog.getContentPane().add(curFloor4, gridBagConstraints);

        jButton2.setText("Retry");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 170, 57, 66);
        Dialog.getContentPane().add(jButton2, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        curFloor.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        curFloor.setText("Username :");
        getContentPane().add(curFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 107, -1, -1));

        curFloor1.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        curFloor1.setText("Password :");
        getContentPane().add(curFloor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 142, -1, -1));

        curFloor2.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        curFloor2.setText("Verification");
        getContentPane().add(curFloor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 35, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 228, -1, -1));
        getContentPane().add(givenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 103, 98, -1));
        getContentPane().add(givenKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 176, 96, -1));

        curFloor3.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        curFloor3.setText("Key :");
        getContentPane().add(curFloor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 180, -1, -1));
        getContentPane().add(givenPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 138, 96, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name= givenName.getText();        // TODO add your handling code here:
        
        char[] temp= givenPass.getPassword();
        String pass= String.valueOf(temp);
        
        temp= givenKey.getPassword();
        String key= String.valueOf(temp);
        
        if(name.equals(authName) && pass.equals(authPass) && key.equals(authKey))
        {
            this.dispose();
            new Admin().setVisible(true);
        }
        else
        {
            this.dispose();
            Dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dialog.dispose();
        new Verify().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog;
    private javax.swing.JLabel curFloor;
    private javax.swing.JLabel curFloor1;
    private javax.swing.JLabel curFloor2;
    private javax.swing.JLabel curFloor3;
    private javax.swing.JLabel curFloor4;
    private javax.swing.JPasswordField givenKey;
    private javax.swing.JTextField givenName;
    private javax.swing.JPasswordField givenPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
